services:
  web:
    container_name: gpsf-website
    image: gpsf-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "127.0.0.1:3004:3004"
    environment:
      NODE_ENV: production
